# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
